[workspace]
members = ["device", "cameleon", "gentl", "genapi", "impl"]
resolver = "2"

[workspace.metadata.release]
# Use single tag for all crates (config for `cargo release`):
tag-name = "cameleon-v{{version}}"
